version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=chat_app_database
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - .:/chat_app_database

  chat-server:
    build:
      context: ./
    restart: always
    ports:
      - 33000:33000
    depends_on:
      - db
