version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=chat_app_database
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/chat_app_database

  chat-server:
    build: server/
    command: python ./server.py
    ports:
      - 33000:33000
    depends_on:
      - db

  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - chat-server
